/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author josch
 */
public class MainUI extends javax.swing.JFrame {

    private GestionConductoresPanel gestionConductoresPanel;
    private GestionRutasPanel gestionRutasPanel;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        gestionConductoresPanel = new GestionConductoresPanel();
        gestionRutasPanel = new GestionRutasPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGestionConductores = new javax.swing.JButton();
        btnGestionAutobuses = new javax.swing.JButton();
        btnReservasyCompras = new javax.swing.JButton();
        btnGestionRutas = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setFocusTraversalPolicyProvider(true);

        btnGestionConductores.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGestionConductores.setText("Gestión conductores");
        btnGestionConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionConductoresActionPerformed(evt);
            }
        });

        btnGestionAutobuses.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGestionAutobuses.setText("Gestion Autobuses");
        btnGestionAutobuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionAutobusesActionPerformed(evt);
            }
        });

        btnReservasyCompras.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnReservasyCompras.setText("Reservas y ventas de billetes");
        btnReservasyCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasyComprasActionPerformed(evt);
            }
        });

        btnGestionRutas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGestionRutas.setText("Gestion Rutas");
        btnGestionRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionRutasActionPerformed(evt);
            }
        });

        btnFacturacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnFacturacion.setText("Facturacion");
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Caribeños");

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenido (Nombre Usuario) al administrador de Buses");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionConductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionAutobuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservasyCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGestionAutobuses, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGestionConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservasyCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(292, Short.MAX_VALUE))
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionRutasActionPerformed

        resetButtonColors();

        btnGestionRutas.setBackground(new java.awt.Color(0, 153, 204));
        btnGestionRutas.setForeground(java.awt.Color.WHITE);

        gestionRutasPanel.actualizarDatos();

        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionRutasPanel, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btnGestionRutasActionPerformed

    private void btnReservasyComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasyComprasActionPerformed

        resetButtonColors();


        btnReservasyCompras.setBackground(new java.awt.Color(0, 153, 204));
        btnReservasyCompras.setForeground(java.awt.Color.WHITE);

        ReservaYCompraPanel gestionRutas = new ReservaYCompraPanel();
        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionRutas, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btnReservasyComprasActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed

        resetButtonColors();

        btnFacturacion.setBackground(new java.awt.Color(0, 153, 204));
        btnFacturacion.setForeground(java.awt.Color.WHITE);

        FacturacionPanel gestionRutas = new FacturacionPanel();
        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionRutas, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnGestionAutobusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAutobusesActionPerformed

        resetButtonColors();


        btnGestionAutobuses.setBackground(new java.awt.Color(0, 153, 204));
        btnGestionAutobuses.setForeground(java.awt.Color.WHITE);

        GestionAutubusesPanel gestionRutas = new GestionAutubusesPanel();
        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionRutas, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btnGestionAutobusesActionPerformed

    private void btnGestionConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionConductoresActionPerformed

        resetButtonColors();

        btnGestionConductores.setBackground(new java.awt.Color(0, 153, 204));
        btnGestionConductores.setForeground(java.awt.Color.WHITE);

        gestionConductoresPanel.actualizarDatos();
        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionConductoresPanel, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btnGestionConductoresActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        resetButtonColors();
        
        btnClientes.setBackground(new java.awt.Color(0, 153, 204));
        btnClientes.setForeground(java.awt.Color.WHITE);
        
        GestionClientesPanel gestionClientes = new GestionClientesPanel();
        panelMain.removeAll();
        panelMain.setLayout(new java.awt.BorderLayout());
        panelMain.add(gestionClientes, java.awt.BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();  
    }//GEN-LAST:event_btnClientesActionPerformed

    // Método para resetear colores de botones
    private void resetButtonColors() {
        java.awt.Color defaultColor = javax.swing.UIManager.getColor("Button.background");
        java.awt.Color defaultForeground = javax.swing.UIManager.getColor("Button.foreground");

        btnGestionRutas.setBackground(defaultColor);
        btnGestionRutas.setForeground(defaultForeground);
        btnGestionAutobuses.setBackground(defaultColor);
        btnGestionAutobuses.setForeground(defaultForeground);
        btnGestionConductores.setBackground(defaultColor);
        btnGestionConductores.setForeground(defaultForeground);
        btnReservasyCompras.setBackground(defaultColor);
        btnReservasyCompras.setForeground(defaultForeground);
        btnFacturacion.setBackground(defaultColor);
        btnFacturacion.setForeground(defaultForeground);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnGestionAutobuses;
    private javax.swing.JButton btnGestionConductores;
    private javax.swing.JButton btnGestionRutas;
    private javax.swing.JButton btnReservasyCompras;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
