name: Java CI with Ant

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v4
- name: Set up JDK 21
  uses: actions/setup-java@v4
  with:
    java-version: '21'  # Usa una versión estable, como 21 o 17
    distribution: 'temurin'
    cache: maven
- name: Run Ant Jar
  run: ant -noinput -buildfile build.xml jar